<?php

    $this->headTitle('Cadastro de Formulário');

    $this->mainMenu()->setActiveItemId('quiz');
    $this->mainMenu()->setActiveListItemId('Perguntas');

    $this->pageBreadcrumbs()->setItems([
                'Inicio'=>$this->url('home'),
                'Gerenciamento de Formulário' => $this->url('quizForm'),
                'Cadastro de Formulário' => $this->url('quizForm', ['action'=>'add'])
                ]);

    $form->get('name')
         ->setAttributes(['class'=>'form-control',
                          'placeholder'=>'Nome']);

    $form->get('local')
         ->setAttributes(['class'=>'form-control',
                          'placeholder'=>'Localização']);

    $form->get('sequence')
         ->setAttributes(['class'=>'form-control', 'value' => '1']);

    $form->get('status')
         ->setAttributes(['class'=>'form-control', 'value' => '1']);

    $form->get('id_produto')
         ->setAttributes(['class'=>'form-control']);

    $form->get('submit')->setAttributes(['class'=>'btn btn-danger']);

    $form->prepare();
?>

<div class="row">
    <?= $this->partial('cms/partial/alert'); ?>
</div>
<div class="row">

    <div class="col">
        <h3>Cadastro de Formulário</h3>
        <p> Por favor preencha o seguinte formulário e clique no botão <i>Criar</i>. </p>
    </div>
</div>

<?= $this->form()->openTag($form); ?>

    <div class="row">
        <div class="col-md-6">

            <div class="form-group">
                <?= $this->formLabel($form->get('name')); ?>
                <?= $this->formElement($form->get('name')); ?>
                <?= $this->formElementErrors($form->get('name')); ?>
            </div>

        </div>

        <div class="col-md-3">
            <div class="form-group">
                <?= $this->formLabel($form->get('sequence')); ?>
                <?= $this->formElement($form->get('sequence')); ?>
                <?= $this->formElementErrors($form->get('sequence')); ?>
            </div>
        </div>
        <div class="material-switch form-group">
            <span>Status</span><br>
            <?= $this->formCheckbox($form->get('status')); ?>
            <?= $this->formLabel($form->get('status')); ?>
            <?= $this->formElementErrors($form->get('status')); ?>
            <span class='status_description'></span>
        </div>

    </div>
    <div class="row">

        <div class="col-md-6">
            <div class="form-group">
                <?= $this->formLabel($form->get('local')); ?>
                <?= $this->formElement($form->get('local')); ?>
                <?= $this->formElementErrors($form->get('local')); ?>
            </div>
        </div>

        <div class="col-md-6">

            <div class="form-group">
                <?= $this->formLabel($form->get('id_produto')); ?>
                <?= $this->formElement($form->get('id_produto')); ?>
                <?= $this->formElementErrors($form->get('id_produto')); ?>
            </div>

        </div>
    </div>
    <div class="row">
        <div class="col-md-6">

            <?= $this->formElement($form->get('submit')); ?>

        </div>
    </div>

<?= $this->form()->closeTag(); ?>

