<?php
    $this->headTitle('Visualizar Formulário');

    $this->mainMenu()->setActiveItemId('quiz');
    $this->mainMenu()->setActiveListItemId('Formulários');

    $this->pageBreadcrumbs()->setItems([
                'Inicio'=>$this->url('home'),
                'Gerenciamento de Formulários'=>$this->url('quizForm'),
                'Visualizar Formulário'=>$this->url('quizForm', ['action'=>'edit'])
                ]);

?>
<div class="row">
    <?= $this->partial('cms/partial/alert'); ?>
</div>
<h3>Visualizar Formulário </h3>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
            <tr>
                <th>Nome:</th>
                <td><?= $this->escapeHtml($questionForm->getName()); ?></th>
            </tr>
            <tr>
                <th>Local:</th>
                <td><?= $this->escapeHtml($questionForm->getLocal()); ?></th>
            </tr>
            <tr>
                <th>Ordem:</th>
                <td><?= $this->escapeHtml($questionForm->getSequence()); ?></th>
            </tr>
            <tr>
                <th>Produto:</th>
                <td><?= $this->escapeHtml($questionForm->getIdProduto()->getNome()); ?></th>
            </tr>
            <tr>
                <th>Status:</th>
                <td><?= $this->escapeHtml($questionForm->getStatusAsString()); ?></th>
            </tr>
        </table>
    </div>
</div>
