<h1>Um erro aconteceu</h1>
<h2><?= $this->message; ?></h2>

<?php if (! empty($this->display_exceptions)) : ?>
    <?php if (isset($this->exception)
        && ($this->exception instanceof \Exception || $this->exception instanceof \Error)) : ?>
<hr/>

<h2>Informação adicional:</h2>
<h3><?= get_class($this->exception); ?></h3>
<dl>
    <dt>Arquivo:</dt>
    <dd>
        <pre><?= $this->exception->getFile(); ?>:<?= $this->exception->getLine(); ?></pre>
    </dd>
    <dt>Mensagem:</dt>
    <dd>
        <pre><?= $this->escapeHtml($this->exception->getMessage()); ?></pre>
    </dd>
    <dt>Pilha de rastreamento:</dt>
    <dd>
        <pre><?= $this->escapeHtml($this->exception->getTraceAsString()); ?></pre>
    </dd>
</dl>

        <?php if ($ex = $this->exception->getPrevious()) : ?>
<hr/>

<h2>Exceções anteriores:</h2>
<ul class="list-unstyled">
            <?php $icount = 0; ?>
            <?php while ($ex) : ?>
    <li>
        <h3><?= get_class($ex); ?></h3>
        <dl>
            <dt>Arquivo:</dt>
            <dd>
                <pre><?= $ex->getFile() ?>:<?= $ex->getLine(); ?></pre>
            </dd>
            <dt>Mensagem:</dt>
            <dd>
                <pre><?= $this->escapeHtml($ex->getMessage()); ?></pre>
            </dd>
            <dt>Pilha de rastreamento:</dt>
            <dd>
                <pre><?= $this->escapeHtml($ex->getTraceAsString()); ?></pre>
            </dd>
        </dl>
    </li>
                <?php
                $ex = $ex->getPrevious();
                if (++$icount >= 50) {
                    echo '<li>Pode haver mais exceções, mas não temos memória suficiente para processá-las.</li>';
                    break;
                }
                ?>
            <?php endwhile ?>
</ul>
        <?php endif ?>
    <?php else : ?>
        <h3>Nenhuma exceção disponível.</h3>
    <?php endif ?>
<?php endif ?>
