<?php
    $this->headTitle('Adiconar Função');

    $this->mainMenu()->setActiveItemId('admin');
    $this->mainMenu()->setActiveListItemId('Funções');

    $this->pageBreadcrumbs()->setItems([
                'Inicio'=>$this->url('home'),
                'Gerenciamento de Funções'=>$this->url('roles'),
                'Adiconar Função'=>$this->url('roles', ['action'=>'add'])
                ]);

    $form->get('name')->setAttributes([
        'class'=>'form-control',
        'placeholder'=>'Digite um nome'
        ]);

    $form->get('description')->setAttributes([
        'class'=>'form-control',
        'placeholder'=>'Digite uma descrição'
        ]);

    $form->get('inherit_roles[]')->setAttributes([
        'class'=>'form-control',
        ]);

    $form->get('submit')->setAttributes(['class'=>'btn btn-danger']);

    $form->prepare();
?>
<div class="row">
    <?= $this->partial('cms/partial/alert'); ?>
</div>
<div class="row">

    <div class="col">
        <h3>Adicionar Função</h3>
        <p> Por favor preencha o seguinte formulário e clique no botão <i>Criar</i>. </p>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('name')); ?>
            <?= $this->formElement($form->get('name')); ?>
            <?= $this->formElementErrors($form->get('name')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('description')); ?>
            <?= $this->formElement($form->get('description')); ?>
            <?= $this->formElementErrors($form->get('description')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('inherit_roles[]')); ?>
            <?= $this->formElement($form->get('inherit_roles[]')); ?>
            <?= $this->formElementErrors($form->get('inherit_roles[]')); ?>
        </div>

        <?= $this->formElement($form->get('csrf')); ?>

        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>




