<?php
    $this->headTitle('Editar Função');

    $this->mainMenu()->setActiveItemId('admin');
    $this->mainMenu()->setActiveListItemId('Funções');

    $this->pageBreadcrumbs()->setItems([
                'Inicio'=>$this->url('home'),
                'Gerenciamento de Funções'=>$this->url('roles'),
                'Editar Função'=>$this->url('roles', ['action'=>'edit', 'id'=>$role->getId()])
                ]);

    $form->get('name')->setAttributes([
        'class'=>'form-control',
        'placeholder'=>'Digite um nome'
        ]);

    $form->get('description')->setAttributes([
        'class'=>'form-control',
        'placeholder'=>'Digite uma descrição'
        ]);

    $form->get('inherit_roles[]')->setAttributes([
        'class'=>'form-control',
        ]);


    $form->get('submit')
            ->setAttributes(['class'=>'btn btn-danger'])
            ->setValue('Editar');

    $form->prepare();
?>
<div class="row">
    <?= $this->partial('cms/partial/alert'); ?>
</div>
<div class="row">
    <div class="col">
        <h3>Editar Função <?= $this->escapeHtml($role->getName()); ?></h3>
    </div>
    <div class="col text-right">
        <a class="btn btn-sm btn-outline-primary"
           href="<?= $this->url('roles', ['action'=>'editPermissions', 'id'=>$role->getId()]) ?>">
          <i class="far fa-edit"></i> Editar Permissões
        </a>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('name')); ?>
            <?= $this->formElement($form->get('name')); ?>
            <?= $this->formElementErrors($form->get('name')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('description')); ?>
            <?= $this->formElement($form->get('description')); ?>
            <?= $this->formElementErrors($form->get('description')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('inherit_roles[]')); ?>
            <?= $this->formElement($form->get('inherit_roles[]')); ?>
            <?= $this->formElementErrors($form->get('inherit_roles[]')); ?>
        </div>

        <?= $this->formElement($form->get('csrf')); ?>

        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>

