<?php
    $this->headTitle('Visualizar Função');

    $this->mainMenu()->setActiveItemId('admin');
    $this->mainMenu()->setActiveListItemId('Funções');

    $this->pageBreadcrumbs()->setItems([
                'Inicio'=>$this->url('home'),
                'Gerenciamento de Funções'=>$this->url('roles'),
                'Visualizar Função'=>$this->url('roles', ['action'=>'view', 'id'=>$role->getId()])
                ]);
?>

<div class="row">
    <?= $this->partial('cms/partial/alert'); ?>
</div>
<div class="row">

    <div class="col">
        <h3>Visualizar Função</h3>
    </div>
    <div class="col text-right">
        <a class="btn btn-sm btn-outline-primary" href="<?= $this->url('roles',
                    ['action'=>'edit', 'id'=>$role->getId()]); ?>">
                <i class="far fa-edit"></i> Editar Função
        </a>
    </div>

</div>

<div class="row">
    <div class="col-md-8">
        <table class="table table-striped table-bordered">
             <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($role->getId()) ?></th>
            </tr>
            <tr>
                <th>Nome:</th>
                <td><?= $this->escapeHtml($role->getName()) ?></th>
            </tr>
            <tr>
                <th>Descrição:</th>
                <td><?= $this->escapeHtml($role->getDescription()) ?></th>
            </tr>
            <tr>
                <th>Data de Criação:</th>
                <td><?= $this->escapeHtml($role->getDateCreated()) ?></th>
            </tr>
        </table>
    </div>
</div>

<div class="row">

    <div class="col">
        <h3>Visualizar Permissões</h3>
    </div>
    <div class="col text-right">
        <a class="btn btn-sm btn-outline-primary"
           href="<?= $this->url('roles', ['action'=>'editPermissions', 'id'=>$role->getId()]) ?>">
          <i class="far fa-edit"></i> Editar Permissões
        </a>

    </div>

</div>

<div class="row">
    <div class="col-md-8">
        <table class="table table-striped table-bordered">
            <tr>
                <th>Nome</th>
                <th>Descrição</th>
            </tr>
            <?php foreach($allPermissions as $permission): ?>
            <tr>
                <td>
                    <input type="checkbox" disabled
                           <?php if (isset($effectivePermissions[$permission->getName()])) echo 'checked'; ?>>
                    <?= $this->escapeHtml($permission->getName()) ?>
                    <?php if (isset($effectivePermissions[$permission->getName()]) && $effectivePermissions[$permission->getName()]=='inherited'): ?>
                    <em>(inherited)</em>
                    <?php endif; ?>
                </td>
                <td><?= $this->escapeHtml($permission->getDescription()) ?></td>
            </tr>
            <?php endforeach; ?>
        </table>
    </div>
</div>
