<?php

    $this->headTitle('Contratos');

    $this->mainMenu()->setActiveItemId('implantation');
    $this->mainMenu()->setActiveListItemId('Processo Concluído');

    $this->pageBreadcrumbs()->setItems([
                'Inicio'=>$this->url('home'),
                'Gerenciamento de Contratos em Processo Concluido'=>$this->url('implantation'),
                ]);
?>
<div class="row">
    <?= $this->partial('cms/partial/alert'); ?>
</div>
<div class="row">
    <div class="col">
        <h3>Gerenciamento de Contratos em Processo Concluido</h3>
    </div>
</div>

<div class="row">
    <?= $this->partial('cms/partial/filter', ['search'=>$search, 'operators' => $operators]); ?>
</div>
<div class="table-responsive top-margin-10">
    <table class="table table-striped table-bordered table-hover dataTables">
        <thead class="thead-dark">
            <tr>
                <th>Contrato</th>
                <th>Cliente</th>
                <th>Implantado</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($datas as $data): ?>
            <tr>
                <td>
                    <?= $data['cotIdcontrato']; ?>
                </td>
                <td>
                    <?= $data['cliNome']; ?>
                </td>
                <td>
                    <?= $data['cliImplantacao'] == 1 ? "Sim" : "Não"; ?>
                </td>
                <td>
                    <?php if($data['cliImplantacao'] == 0) { ?>
                        <nobr>
                            <a class="btn btn-sm btn-info hoverable-scale"
                               href="<?= $this->url('deployment_schedule',
                                                    ['action'=>'add',
                                                     'id'=>$data['cliIdcliente']]); ?>"
                               title="Inserir Agendamento">
                                <i class="far fa-edit"></i>
                            </a>
                        </nobr>
                    <?php } ?>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
