<?php

    $this->headTitle('Cadastro de Campo para Pergunta');

    $this->mainMenu()->setActiveItemId('quiz');
    $this->mainMenu()->setActiveListItemId('Perguntas');

    $texto = $fields ? "Edição de Campo para pergunta" : 'Cadastro de Campo para Pergunta';
    $this->pageBreadcrumbs()->setItems([
                'Inicio'=>$this->url('home'),
                'Gerenciamento de Campos para Perguntas'=>$this->url('quiz'),
                $texto =>$this->url('quiz', ['action'=>'add'])
                ]);

?>
<div class="container" id="search-form">

    <?php if (isset($fields) && count($fields) > 0) { ?>
        <div class="clone" data-index="<?= count($fields); ?>" data-noclone="true">
            <div class="row">
                <div class="col m6">
                    <label>Label</label>
                    <input type="text" name="question_field[label][]" class="form-control">
                </div>
                <div class="col m3">
                    <label>Sequence</label>
                    <input type="number" name="question_field[sequence][]" class="form-control">
                </div>
                <div class="col m3 remove">
                    <label>Remover</label><br>
                    <button type="button" class="btn btn-danger remove-line hoverable-scale">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
            </div>
        </div>
    <?php foreach($fields as $key => $field) { ?>

            <div class="cloned cloned_<?= $key+1; ?>" data-index="<?= $key+1; ?>">
                <div class="row">
                    <div class="col m6">
                        <label>Label</label>
                        <input type="text"
                               name="question_field[label][]"
                               class="form-control"
                               value="<?= $field->getLabel(); ?>">
                    </div>
                    <div class="col m3">
                        <label>Sequence</label>
                        <input type="number"
                               name="question_field[sequence][]"
                               class="form-control"
                               value="<?= $field->getSequence(); ?>"
                               >
                    </div>
                    <div class="col m3 remove">
                        <label>Remover</label><br>
                        <button type="button"
                                class="btn btn-danger remove-line hoverable-scale"
                                data-index="<?= $key+1; ?>">
                            <i class="fas fa-times"></i>
                        </button>
                    </div>
                </div>
            </div>

    <?php }
    } else {
    ?>
        <div class="clone" data-index="0">
            <div class="row">
                <div class="col m6">
                    <label>Label</label>
                    <input type="text" name="question_field[label][]" class="form-control">
                </div>
                <div class="col m3">
                    <label>Sequence</label>
                    <input type="number" name="question_field[sequence][]" class="form-control">
                </div>
                <div class="col m3 remove">
                    <label>Remover</label><br>
                    <button type="button" class="btn btn-danger remove-line hoverable-scale">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
            </div>
        </div>
    <?php } ?>

    <div class="form-group text-right">
        <button type="button" id="add-more" class="btn btn-secondary hoverable-scale">
            <i class="fa fa-plus"></i>
        </button>
    </div>

</div>