<?php

    $this->headTitle('Alterar Campo de Pergunta');

    $this->mainMenu()->setActiveItemId('quiz');
    $this->mainMenu()->setActiveListItemId('Campos');

    $this->pageBreadcrumbs()
         ->setItems(['Inicio' => $this->url('home'),
                     'Gerenciamento de Campos para Perguntas' => $this->url('quizField'),
                     'Editar de Campo de Pergunta' => $this->url('quizField', ['action'=>'edit'])]);

    $form->get('id_question')
         ->setAttributes(['class'=>'form-control',
                          'placeholder'=>'Formulário']);

    $form->get('label')
         ->setAttributes(['class'=>'form-control',
                          'placeholder'=>'Label']);

    $form->get('identifier')
         ->setAttributes(['class'=>'form-control',
                          'placeholder'=>'Identificador']);

    $form->get('value_field')
         ->setAttributes(['class'=>'form-control',
                          'placeholder'=>'Valor']);

    $form->get('type')
         ->setAttributes(['class'=>'form-control',
                          'placeholder'=>'Tipo']);

    $form->get('sequence')
         ->setAttributes(['class'=>'form-control']);

    $form->get('depends_field')
         ->setAttributes(['class'=>'form-control']);

    $form->get('submit')
         ->setAttributes(['class'=>'btn btn-danger'])
         ->setValue('Alterar');

    $form->prepare();
?>
<div class="row">
    <?= $this->partial('cms/partial/alert'); ?>
</div>
<h3>Editar Campo: <?= $this->escapeHtml($questionField->getLabel()) ?></h3>

<?= $this->form()->openTag($form); ?>

    <?php if($idValue){ ?>
        <input type="hidden" name="default_value" value=<?= $idValue; ?>>
    <?php } ?>

    <div class="row">

        <div class="col-md-6">
            <div class="form-group">
                <?= $this->formLabel($form->get('id_question')); ?>
                <?= $this->formElement($form->get('id_question')); ?>
                <?= $this->formElementErrors($form->get('id_question')); ?>
            </div>
        </div>

    </div>
    <div class="row">

        <div class="col-md-6">
            <div class="form-group">
                <?= $this->formLabel($form->get('depends_field')); ?>
                <?= $this->formElement($form->get('depends_field')); ?>
                <?= $this->formElementErrors($form->get('depends_field')); ?>
            </div>
        </div>

    </div>
    <div class="row">
        <div class="col-md-6">

            <div class="form-group">
                <?= $this->formLabel($form->get('label')); ?>
                <?= $this->formElement($form->get('label')); ?>
                <?= $this->formElementErrors($form->get('label')); ?>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">

            <div class="form-group">
                <?= $this->formLabel($form->get('identifier')); ?>
                <?= $this->formElement($form->get('identifier')); ?>
                <?= $this->formElementErrors($form->get('identifier')); ?>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">

            <div class="form-group">
                <?= $this->formLabel($form->get('value_field')); ?>
                <?= $this->formElement($form->get('value_field')); ?>
                <?= $this->formElementErrors($form->get('value_field')); ?>
            </div>
        </div>
    </div>
    <div class="row">

        <div class="col-md-6">
            <div class="form-group">
                <?= $this->formLabel($form->get('type')); ?>
                <?= $this->formElement($form->get('type')); ?>
                <?= $this->formElementErrors($form->get('type')); ?>
            </div>
        </div>

    </div>
    <div class="row">

        <div class="col-md-6">
            <div class="form-group">
                <?= $this->formLabel($form->get('sequence')); ?>
                <?= $this->formElement($form->get('sequence')); ?>
                <?= $this->formElementErrors($form->get('sequence')); ?>
            </div>
        </div>

    </div>

    <div class="row">
        <div class="col-md-6">
            <?= $this->formElement($form->get('submit')); ?>
        </div>
    </div>
<?= $this->form()->closeTag(); ?>
