<?php

    $this->headTitle('Campos para Perguntas');

    $this->mainMenu()->setActiveItemId('quiz');
    $this->mainMenu()->setActiveListItemId('Campos');

    $this->pageBreadcrumbs()->setItems([
                'Inicio'=>$this->url('home'),
                'Gerenciamento de Campos para Perguntas'=>$this->url('quizField'),
                ]);


    $this->mainMenu()->setActiveItemId('quiz');
    $this->mainMenu()->setActiveListItemId('Perguntas');

    $this->pageBreadcrumbs()
         ->setItems(['Inicio'=>$this->url('home'),
                     'Gerenciamento de Formulário de Perguntas'=>$this->url('quiz')]);

?>
<div class="row">
    <?= $this->partial('cms/partial/alert'); ?>
</div>
<div class="row">
    <div class="col col-md-8">
        <h3>Gerenciamento de Campos para Perguntas</h3>
    </div>
    <div class="col text-right">
        <a class="btn btn-sm btn-outline-primary rounded-circle hoverable-rotate hoverable-rotate-moviment" href="
            <?= $this->url('quizField', ['action'=>'add']); ?>" title="Adicionar">
            <i class="fas fa-plus"></i>
        </a>
    </div>
</div>
<!-- name, form, order, required, status.and question_form_bond -->
<div class="row">
    <?= $this->partial('cms/partial/filter', ['search'=>$search, 'operators' => $operators]); ?>
</div>
<div class="table-responsive top-margin-10">
    <table class="table table-striped table-bordered table-hover dataTables">
        <thead class="thead-dark">
            <tr>
                <th>Pergunta</th>
                <th>Label</th>
                <th>Tipo</th>
                <th>Sequência</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($fields as $field): ?>
            <tr>
                <td>
                    <a href="<?= $this->url('quizField', ['action'=>'view', 'id'=>$field->getId()]); ?>">
                        <?= $this->escapeHtml($field->getQuestionAsString()); ?>
                    </a>
                </td>
                <td>
                    <?= $field->getLabel(); ?>
                </td>
                <td>
                    <?= $field->getTypeAsString(); ?>
                </td>
                <td>
                    <?= $field->getSequence(); ?>
                </td>
                <td>
                    <nobr>
                        <a class="btn btn-sm btn-info hoverable-scale"
                           href="<?= $this->url('quizField', ['action'=>'edit', 'id'=>$field->getId()]); ?>"
                           title="Editar">
                            <i class="far fa-edit"></i>
                        </a>
                        <a class="btn btn-sm btn-danger delete-action hoverable-scale"
                           data-id="<?= $field->getId(); ?>"
                           href="#"
                           title="Remover">
                            <i class="fa fa-trash"></i>
                        </a>
                    </nobr>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>