<?php
    $this->headTitle('Visualizar Campo');

    $this->mainMenu()->setActiveItemId('quiz');
    $this->mainMenu()->setActiveListItemId('Campos');

    $this->pageBreadcrumbs()->setItems([
                'Inicio'=>$this->url('home'),
                'Gerenciamento de Campos para Perguntas'=>$this->url('quizField'),
                'Visualizar Campo'=>$this->url('quizField', ['action'=>'edit'])
                ]);

?>
<div class="row">
    <?= $this->partial('cms/partial/alert'); ?>
</div>
<h3>Visualizar Campo </h3>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
            <tr>
                <th>Pergunta:</th>
                <td><?= $this->escapeHtml($questionField->getQuestionAsString()); ?></th>
            </tr>
            <tr>
                <th>Label:</th>
                <td><?= $this->escapeHtml($questionField->getLabel()); ?></th>
            </tr>
            <tr>
                <th>Identificador:</th>
                <td><?= $this->escapeHtml($questionField->getIdentifier()); ?></th>
            </tr>
            <tr>
                <th>Valor:</th>
                <td><?= $this->escapeHtml($questionField->getValueField()); ?></th>
            </tr>
            <tr>
                <th>Tipo:</th>
                <td><?= $this->escapeHtml($questionField->getTypeAsString()); ?></th>
            </tr>
            <tr>
                <th>Sequencia:</th>
                <td><?= $this->escapeHtml($questionField->getSequence()); ?></th>
            </tr>
            <tr>
                <th>Depende do campo:</th>
                <td><?= $this->escapeHtml($questionField->getDependsField()); ?></th>
            </tr>
        </table>
    </div>
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
            <tr>
                <th>Exemplo:</th>
                <td><?= $input; ?></td>
            </tr>
        </table>
    </div>
</div>