<?php

    $this->headTitle('Adicionar Grupo');

    $this->mainMenu()->setActiveItemId('management');
    $this->mainMenu()->setActiveListItemId('Grupos');

    $this->pageBreadcrumbs()->setItems([
                'Inicio'=>$this->url('home'),
                'Gerenciamento de Grupos'=>$this->url('groups'),
                'Adicionar Grupo'=>$this->url('groups', ['action'=>'add'])
                ]);

    $form->get('name')->setAttributes([
        'class'=>'form-control',
        'placeholder'=>'CRM'
        ]);

    $form->get('status')->setAttributes([
        'class'=>'form-control', 'value' => '1'
        ]);

    $form->get('submit')->setAttributes(['class'=>'btn btn-danger']);

    $form->prepare();
?>

<div class="row">
    <?= $this->partial('cms/partial/alert'); ?>
</div>
<div class="row">

    <div class="col">
        <h3>Adicionar Grupo</h3>
        <p> Por favor preencha o seguinte formulário e clique no botão <i>Criar</i>. </p>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>

        <div class="material-switch form-group">
            <span>Status</span><br>
            <?= $this->formCheckbox($form->get('status')); ?>
            <?= $this->formLabel($form->get('status')); ?>
            <?= $this->formElementErrors($form->get('status')); ?>
            <span class='status_description'></span>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('name')); ?>
            <?= $this->formElement($form->get('name')); ?>
            <?= $this->formElementErrors($form->get('name')); ?>
        </div>

        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>

