<?php
    $this->headTitle('Editar Grupo');

    $this->mainMenu()->setActiveItemId('management');
    $this->mainMenu()->setActiveListItemId('Grupos');

    $this->pageBreadcrumbs()->setItems([
                'Home'=>$this->url('home'),
                'Gerenciamento de Grupos'=>$this->url('groups'),
                'Editar Grupo'=>$this->url('groups', ['action'=>'edit', 'id'=>$wgroup->getId()])
                ]);

        $form->get('name')->setAttributes([
            'class'=>'form-control',
            'placeholder'=>'CRM'
            ]);

        $form->get('status')->setAttributes([
            'class'=>'form-control'
            ]);

        $form->get('submit')
                ->setAttributes(['class'=>'btn btn-danger'])
                ->setValue('Alterar');

        $form->prepare();
?>
<div class="row">
    <?= $this->partial('cms/partial/alert'); ?>
</div>
<div class="row">
    <div class="col">
        <h3>Editar Grupo <?= $this->escapeHtml($wgroup->getName()) ?></h3>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>

        <div class="material-switch form-group">
            <span>Status</span><br>
            <?= $this->formCheckbox($form->get('status')); ?>
            <?= $this->formLabel($form->get('status')); ?>
            <?= $this->formElementErrors($form->get('status')); ?>
            <span class='status_description'></span>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('name')); ?>
            <?= $this->formElement($form->get('name')); ?>
            <?= $this->formElementErrors($form->get('name')); ?>
        </div>

        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>

