<?php
    $this->headTitle('Visualizar Grupo');

    $this->mainMenu()->setActiveItemId('management');
    $this->mainMenu()->setActiveListItemId('Grupos');

    $this->pageBreadcrumbs()->setItems([
                'Home'=>$this->url('home'),
                'Gerenciamento de Grupos'=>$this->url('groups'),
                'Visualizar Grupo'=>$this->url('groups', ['action'=>'view', 'id'=>$workGroup->getId()])
                ]);
?>
<div class="row">
    <?= $this->partial('cms/partial/alert'); ?>
</div>
    <h3>Visualizar Grupo </h3>
<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
             <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($workGroup->getId()); ?></th>
            </tr>
            <tr>
                <th>Name:</th>
                <td><?= $this->escapeHtml($workGroup->getName()); ?></th>
            </tr>
            <tr>
                <th>Status:</th>
                <td><?= $this->escapeHtml($workGroup->getStatusAsString()); ?></th>
            </tr>
        </table>
    </div>
</div>