<?php

    $this->headTitle('Alterar Senha');

    $this->mainMenu()->setActiveItemId('management');
    $this->mainMenu()->setActiveListItemId('Usuários');

    $this->pageBreadcrumbs()->setItems([
                'Início'=>$this->url('home'),
                'Gerencimanento de Usuários'=>$this->url('users'),
                'Alterar Senha'=>$this->url('users', ['action'=>'change-password', 'id'=>$user->getId()])
                ]);

    $form->get('old_password')->setAttributes([
        'class'=>'form-control',
        'placeholder'=>'Informe a senha atual'
        ]);

    $form->get('new_password')->setAttributes([
        'class'=>'form-control',
        'placeholder'=>'Informe a senha nova'
        ]);

    $form->get('confirm_new_password')->setAttributes([
        'class'=>'form-control',
        'placeholder'=>'Confirme a senha nova'
        ]);

    $form->get('submit')->setAttributes(['class'=>'btn btn-danger']);

    $form->prepare();
?>
    <?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
    <?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
    <?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<h3>Alteração de senha para <?= $this->escapeHtml($user->getEmail()) ?></h3>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('old_password')); ?>
            <?= $this->formElement($form->get('old_password')); ?>
            <?= $this->formElementErrors($form->get('old_password')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('new_password')); ?>
            <?= $this->formElement($form->get('new_password')); ?>
            <?= $this->formElementErrors($form->get('new_password')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('confirm_new_password')); ?>
            <?= $this->formElement($form->get('confirm_new_password')); ?>
            <?= $this->formElementErrors($form->get('confirm_new_password')); ?>
        </div>

        <?= $this->formElement($form->get('csrf')); ?>

        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>


