<?php

    $this->headTitle('Editar Usuário');

    $this->mainMenu()->setActiveItemId('management');
    $this->mainMenu()->setActiveListItemId('Usuários');

    $this->pageBreadcrumbs()->setItems([
                'Início'=>$this->url('home'),
                'Gerencimanento de Usuários'=>$this->url('users'),
                'Editar Usuário'=>$this->url('users', ['action'=>'edit', 'id'=>$user->getId()])
                ]);

    $form->get('email')->setAttributes([
        'class'=>'form-control',
        'placeholder'=>'joao.silva@empresa.com'
        ]);

    $form->get('first_name')->setAttributes([
        'class'=>'form-control',
        'placeholder'=>'João'
        ]);

    $form->get('last_name')->setAttributes([
        'class'=>'form-control',
        'placeholder'=>'da Silva'
        ]);

    $form->get('status')->setAttributes([
        'class'=>''
        ]);

    $form->get('roles')->setAttributes([
        'class'=>'form-control'
    ]);

    $form->get('departaments')->setAttributes([
        'class'=>'form-control'
    ]);

    $form->get('submit')
            ->setAttributes(['class'=>'btn btn-danger'])
            ->setValue('Alterar');

    $form->prepare();
?>
<div class="row">
    <?= $this->partial('cms/partial/alert'); ?>
</div>
<div class="row">
    <div class="col">
        <h3>Editar usuário <?= $this->escapeHtml($user->getEmail()) ?></h3>
    </div>
</div>

<?= $this->form()->openTag($form); ?>
    <div class="row">
         <div class="col sm12 m6">

            <div class="material-switch form-group">
                <span>Status</span><br>
                <?= $this->formCheckbox($form->get('status')); ?>
                <?= $this->formLabel($form->get('status')); ?>
                <?= $this->formElementErrors($form->get('status')); ?>
                <span class='status_description'></span>
            </div>

            <div class="form-group">
                <?= $this->formLabel($form->get('email')); ?>
                <?= $this->formElement($form->get('email')); ?>
                <?= $this->formElementErrors($form->get('email')); ?>
            </div>

            <div class="form-group">
                <?= $this->formLabel($form->get('first_name')); ?>
                <?= $this->formElement($form->get('first_name')); ?>
                <?= $this->formElementErrors($form->get('first_name')); ?>
            </div>

            <div class="form-group">
                <?= $this->formLabel($form->get('last_name')); ?>
                <?= $this->formElement($form->get('last_name')); ?>
                <?= $this->formElementErrors($form->get('last_name')); ?>
            </div>

        </div>
        <div class="col sm12 m6 half-trace">
            <div class="form-group">
                <?= $this->formLabel($form->get('roles')); ?>
                <?= $this->formElement($form->get('roles')); ?>
                <?= $this->formElementErrors($form->get('roles')); ?>
            </div>

            <div class="form-group">
                <?= $this->formLabel($form->get('departaments')); ?>
                <?= $this->formElement($form->get('departaments')); ?>
                <?= $this->formElementErrors($form->get('departaments')); ?>
            </div>
            
        </div>
        <div class="w-100"></div>
        <div class="col m12">
            <?= $this->formElement($form->get('submit')); ?>
        </div>
    </div>
<?= $this->form()->closeTag(); ?>

