<?php
    $this->headTitle('Usuários');

    $this->mainMenu()->setActiveItemId('management');
    $this->mainMenu()->setActiveListItemId('Usuários');

    $this->pageBreadcrumbs()->setItems([
                'Início'=>$this->url('home'),
                'Gerencimanento de Usuários'=>$this->url('users'),
                ]);
?>

<div class="row">
    <?= $this->partial('cms/partial/alert'); ?>
</div>
<div class="row">

    <div class="col">
        <h3>Gerenciamento de Usuários</h3>
    </div>
    <div class="col text-right">
        <a class="btn btn-sm btn-outline-primary rounded-circle hoverable-rotate hoverable-rotate-moviment" href="
            <?= $this->url('users', ['action'=>'add']); ?>" title="Adicionar">
            <i class="fas fa-plus"></i>
        </a>
    </div>

</div>
<div class="row">
    <?= $this->partial('cms/partial/filter', ['search'=>$search, 'operators' => $operators]); ?>
</div>

<div class="table-responsive top-margin-10">
    <table class="table table-striped table-bordered table-hover dataTables">
        <thead class="thead-dark">
           <tr>
                <th>E-mail</th>
                <th>Nome</th>
                <th>Função</th>
                <th>Data de Criação</th>
                <th>Status</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($users as $user): ?>
                <tr>
                    <td>
                        <a href="<?= $this->url('users', ['action'=>'view', 'id'=>$user->getId()]); ?>">
                            <?= $this->escapeHtml($user->getEmail()); ?>
                        </a>
                    </td>
                    <td><?= $this->escapeHtml($user->getFirstName()." ".$user->getLastName()); ?></td>
                    <td>
                        <?= $this->escapeHtml($user->getRolesAsString()); ?>
                    </td>
                    <td><?= $this->escapeHtml($user->getDateCreated()->format('d/m/Y')); ?></td>
                    <td>
                        <div class="status_string_<?= $user->getId(); ?>">
                            <?= $this->escapeHtml($user->getStatusAsString()); ?>
                        </div>
                        <div class="material-switch">
                            <input class="status-index" type="checkbox" name="status"
                                   value="<?= $user->getStatus() ;?>"
                                   data-status="<?= $this->escapeHtml($user->getStatusAsString()); ?>"
                                   data-id="<?= $user->getId(); ?>"
                                   id="status_<?= $user->getId(); ?>"
                                   >
                            <label for="status_<?= $user->getId(); ?>"></label>
                        </div>
                    </td>
                    <td>
                        <a class="btn btn-info btn-sm hoverable-scale"
                            href="<?= $this->url('users',['action'=>'edit', 'id'=>$user->getId()]); ?>"
                            title="Editar">
                            <i class="far fa-edit"></i>
                        </a>
                        <a class="btn btn-danger delete-action btn-sm hoverable-scale"
                           data-id="<?= $user->getId(); ?>"
                           href="#"
                           title="Remover">
                            <i class="fa fa-trash"></i>
                        </a>
                        <a class="btn btn-warning btn-sm hoverable-scale"
                           href="<?= $this->url('users', ['action'=>'change-password', 'id'=>$user->getId()]); ?>"
                           title="Alterar Senha">
                            <i class="fas fa-asterisk"></i>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>