<?php
    $this->headTitle('Redefinir senha');

    $form->get('email')->setAttributes(['class'=>'form-control',
                                        'placeholder'=>'Enderço de e-mail']);

    $form->get('submit')->setAttributes(['class'=>'btn btn-large btn-danger']);

    $form->prepare();
?>

<div class="row">
    <div class="col-md-offset-4 col-md-4">
        <?= $this->form()->openTag($form); ?>

        <h2>Resetar senha</h2>

        <p>Informe o seu endereço de e-mail abaixo para redefinir sua senha.</p>

        <?= $this->formElement($form->get('email')); ?>
        <?= $this->formElementErrors($form->get('email')); ?>

        <?= $this->formElement($form->get('captcha')); ?>
        <p class="hint">Informe as letras acima, como você enxergar.</p>

        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->formElement($form->get('csrf')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>
