<?php
    $this->headTitle('Definir nova senha');

    $form->get('new_password')
         ->setAttributes([
            'class'=>'mat-input'])
         ->setLabelAttributes([
                'class' => 'mat-label'
         ]);

    $form->get('confirm_new_password')
         ->setAttributes([
            'class'=>'mat-input'
         ])->setLabelAttributes([
                'class' => 'mat-label'
         ]);

    $form->get('submit')->setAttributes(array(
        'class'=>'btn btn-danger'
        ));
    $form->prepare();
?>

<div class="row">
    <div class="col m12 text-center">
        <h1 class="form-signin-heading-reset">
            <strong>Csec Sistemas</strong>
        </h1>
    </div>
    <div class="w-100"></div>
    <div class="col-md-6 offset-md-3">

        <?= $this->form()->openTag($form); ?>

        <div class="text-center">
            <!-- <h4>Definir nova senha</h4> -->
            <p>Informe sua nova senha no formulário abaixo</p>
        </div>

        <div class="mat-div">
            <?= $this->formLabel($form->get('new_password')); ?>
            <?= $this->formElement($form->get('new_password')); ?>
            <?= $this->formElementErrors($form->get('new_password')); ?>
        </div>

        <div class="mat-div">
            <?= $this->formLabel($form->get('confirm_new_password')); ?>
            <?= $this->formElement($form->get('confirm_new_password')); ?>
            <?= $this->formElementErrors($form->get('confirm_new_password')); ?>
        </div>

        <div class="row">
            <div class="col m8">
                <button class="btn btn-lg btn-danger btn-block" type="submit">
                     <i class="fas fa-unlock-alt"></i> Alterar Senha
                </button>
            </div>
        </div>

        <?= $this->formElement($form->get('csrf')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>

