<?php

    $this->headTitle('Alteração de Produto');

    $this->mainMenu()->setActiveItemId('quiz');
    $this->mainMenu()->setActiveListItemId('Produtos');

    $this->pageBreadcrumbs()
         ->setItems(['Inicio'=>$this->url('home'),
                     'Gerenciamento de Produtos'=>$this->url('produto'),
                     'Editar Produto'=>$this->url('produto', ['action'=>'edit'])]);

    $form->get('nome')
         ->setAttributes(['class'=>'form-control',
                          'placeholder'=>'Nome']);

    $form->get('status')
         ->setAttributes(['class'=>'form-control']);

    $form->get('submit')
         ->setAttributes(['class'=>'btn btn-danger'])
         ->setValue('Alterar');

    $form->prepare();
?>
<div class="row">
    <?= $this->partial('cms/partial/alert'); ?>
</div>
<h3>Editar Produto: <?= $this->escapeHtml($produto->getNome()) ?></h3>

<?= $this->form()->openTag($form); ?>

    <div class="row">
        <div class="col-md-6">

            <div class="form-group">
                <?= $this->formLabel($form->get('nome')); ?>
                <?= $this->formElement($form->get('nome')); ?>
                <?= $this->formElementErrors($form->get('nome')); ?>
            </div>

        </div>
        <div class="col-md-3">

            <div class="material-switch form-group">
                <span>Status</span><br>
                <?= $this->formCheckbox($form->get('status')); ?>
                <?= $this->formLabel($form->get('status')); ?>
                <?= $this->formElementErrors($form->get('status')); ?>
                <span class='status_description'></span>
            </div>
        </div>

    </div>
    <div class="row">
        <div class="col-md-6">

            <?= $this->formElement($form->get('submit')); ?>

        </div>
    </div>
<?= $this->form()->closeTag(); ?>
