<?php
    $this->headTitle('Produtos');

    $this->mainMenu()->setActiveItemId('quiz');
    $this->mainMenu()->setActiveListItemId('Produtos');

    $this->pageBreadcrumbs()
         ->setItems(['Inicio'=>$this->url('home'),
                     'Gerenciamento de Produtos'=>$this->url('produto')]);
?>
<div class="row">
    <?= $this->partial('cms/partial/alert'); ?>
</div>
<div class="row">
    <div class="col col-md-8">
        <h3>Gerenciamento de Produtos</h3>
    </div>
    <div class="col text-right">
        <a class="btn btn-sm btn-outline-primary rounded-circle hoverable-rotate hoverable-rotate-moviment" href="
            <?= $this->url('produto', ['action'=>'add']); ?>" title="Adicionar">
            <i class="fas fa-plus"></i>
        </a>
    </div>
</div>
<!-- name, form, order, required, status.and question_form_bond -->
<div class="row">
    <?= $this->partial('cms/partial/filter', ['search'=>$search, 'operators' => $operators]); ?>
</div>
<div class="table-responsive top-margin-10">
    <table class="table table-striped table-bordered table-hover dataTables">
        <thead class="thead-dark">
            <tr>
                <th>Nome</th>
                <th>Status</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($forms as $produto): ?>
            <tr>
                <td>
                    <a href="<?= $this->url('produto', ['action'=>'view', 'id'=>$produto->getId()]); ?>">
                        <?= $this->escapeHtml($produto->getNome()); ?>
                    </a>
                </td>

                <td>
                    <div class="status_string_<?= $produto->getId(); ?>">
                        <?= $this->escapeHtml($produto->getStatusAsString()); ?>
                    </div>
                    <div class="material-switch">
                        <input class="status-index" type="checkbox" name="status"
                               value="<?= $produto->getStatus() ;?>"
                               data-status="<?= $this->escapeHtml($produto->getStatusAsString()); ?>"
                               data-id="<?= $produto->getId(); ?>"
                               id="status_<?= $produto->getId(); ?>"
                               >
                        <label for="status_<?= $produto->getId(); ?>"></label>
                    </div>
                </td>
                <td>
                    <nobr>
                        <a class="btn btn-sm btn-info hoverable-scale"
                           href="<?= $this->url('produto', ['action'=>'edit', 'id'=>$produto->getId()]); ?>"
                           title="Editar">
                            <i class="far fa-edit"></i>
                        </a>
                        <a class="btn btn-sm btn-danger delete-action hoverable-scale"
                           data-id="<?= $produto->getId(); ?>"
                           href="#"
                           title="Remover">
                            <i class="fa fa-trash"></i>
                        </a>
                    </nobr>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>

