<?php
    $this->headTitle('Visualizar Produto');

    $this->mainMenu()->setActiveItemId('quiz');
    $this->mainMenu()->setActiveListItemId('Produtos');

    $this->pageBreadcrumbs()->setItems([
                'Inicio'=>$this->url('home'),
                'Gerenciamento de Produtos'=>$this->url('produto'),
                'Visualizar Produto'=>$this->url('produto', ['action'=>'edit'])
                ]);

?>
<div class="row">
    <?= $this->partial('cms/partial/alert'); ?>
</div>
<h3>Visualizar Produto</h3>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
            <tr>
                <th>Nome:</th>
                <td><?= $this->escapeHtml($produto->getNome()); ?></th>
            </tr>
            <tr>
                <th>Status:</th>
                <td><?= $this->escapeHtml($produto->getStatusAsString()); ?></th>
            </tr>
        </table>
    </div>
</div>
