<?php
    $this->headTitle('Agendar Implantação');

    $this->mainMenu()->setActiveItemId('implantation');
    $this->mainMenu()->setActiveListItemId('AGENDA - TÉCNICO');

    $this->pageBreadcrumbs()->setItems([
                'Inicio'=>$this->url('home'),
                'Gerenciamento de Agendamento de Implantação'=>$this->url('deployment_schedule'),
                'Adicionar Agendamento'=>$this->url('deployment_schedule', ['action'=>'add'])
                ]);

    $form->get('id_client')->setAttributes([
        'value' => $id_client]);

    $form->get('client_name')->setAttributes([
        'class'=>'form-control',
        'placeholder'=>'Cliente Nome',
        'value' => $cliNome['cliNome'],
        'readonly' => 'readonly'
        ]);

    $form->get('date')->setAttributes([
        'class'=>'form-control datepicker',
        'placeholder'=>'Data'
        ]);

    $form->get('time')->setAttributes([
        'class'=>'form-control timepicker',
        'placeholder'=>'Time'
        ]);

    $form->get('status')->setAttributes([
        'class'=>'form-control', 'value' => '1'
        ]);

    $form->get('submit')->setAttributes(['class'=>'btn btn-danger']);

    $form->prepare();
?>

<div class="row">
    <?= $this->partial('cms/partial/alert'); ?>
</div>
<div class="row">

    <div class="col">
        <h3>Adicionar Implantação</h3>
        <p> Por favor preencha o seguinte formulário e clique no botão <i>Criar</i>. </p>
    </div>
</div>

<?= $this->form()->openTag($form); ?>

    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <?= $this->formLabel($form->get('client_name')); ?>
                <?= $this->formElement($form->get('client_name')); ?>
                <?= $this->formElementErrors($form->get('client_name')); ?>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <?= $this->formElement($form->get('id_client')); ?>
            </div>
        </div>
    </div>
    <div class="row">

        <div class="col-md-4 col-xs-6">
            <div class="form-group">
                <?= $this->formLabel($form->get('date')); ?>
                <?= $this->formElement($form->get('date')); ?>
                <?= $this->formElementErrors($form->get('date')); ?>
            </div>
        </div>
        <div class="col-md-1 col-xs-3">
            <div class="form-group">
                <label>&nbsp</label><br>
                <input type="button" value="hoje" class="today btn btn-primary hoverable-scale">
            </div>
        </div>
        <div class="col-md-1 col-xs-3">
            <div class="form-group">
                <label>&nbsp</label><br>
                <input type="button" value="amanhã" class="tomorrow btn btn-primary hoverable-scale">
            </div>
        </div>

    </div>
    <div class="row">
        <div class="col-md-4">

            <div class="form-group">
                <?= $this->formLabel($form->get('time')); ?>
                <?= $this->formElement($form->get('time')); ?>
                <?= $this->formElementErrors($form->get('time')); ?>
            </div>
        </div>
        <div class="col-md-2 text-right">
            <div class="form-group">
                <label>&nbsp</label><br>
                <input type="button" value="agora" class="now btn btn-primary hoverable-scale">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <?= $this->formLabel($form->get('status')); ?>
                <?= $this->formElement($form->get('status')); ?>
                <?= $this->formElementErrors($form->get('status')); ?>
            </div>

            <?= $this->formElement($form->get('submit')); ?>

        </div>
    </div>

<?= $this->form()->closeTag(); ?>

