<?php

    $this->headTitle('Agendar Implantação');
    $this->headLink()
          ->prependStylesheet($this->basePath('css/min/jquery.timepicker.min.css'));

    $this->mainMenu()->setActiveItemId('implantation');
    $this->mainMenu()->setActiveListItemId('AGENDA - TÉCNICO');

    $this->pageBreadcrumbs()->setItems([
                'Inicio'=>$this->url('home'),
                'Gerenciamento de Agendamento de Implantação'=>$this->url('deployment_schedule'),
                'Editar Agendamento'=>$this->url('deployment_schedule', ['action'=>'edit'])
                ]);

    $form->get('client_name')->setAttributes([
        'class'=>'form-control',
        'placeholder'=>'Cliente',
        'readonly' => 'readonly',
        'id' => 'client_name'
        ]);

    $form->get('date')->setAttributes([
        'class'=>'form-control',
        'placeholder'=>'Data',
        'readonly' => 'readonly',
        'autocomplete' => 'off',
        'id' => 'date'
        ]);

    $form->get('time')->setAttributes([
        'class'=>'form-control',
        'placeholder'=>'Horário',
        'readonly' => 'readonly',
        'autocomplete' => 'off',
        'id' => 'time'
        ]);

    $form->get('time_end')->setAttributes([
        'class'=>'form-control timepicker',
        'placeholder'=>'Horário de Término',
        'readonly' => 'readonly',
        'autocomplete' => 'off',
        'id' => 'time_end'
        ]);

    $form->get('status')->setAttributes([
        'class'=>'form-control',
        ]);

    $form->get('submit')
            ->setAttributes(['class'=>'btn btn-success'])
            ->setValue('Confirmar');

    $form->prepare();
?>

<div class="row">
    <?= $this->partial('cms/partial/alert'); ?>
</div>
<div class="row">
    <div class="col-sm-10">
        <h3>Iniciar Agendamento: <?= $this->escapeHtml($deploymentSchedule->getClientName()); ?></h3>
    </div>
    <div class="col-sm-2">
        <label class="time"></label>
    </div>
</div>
<ul class="nav nav-tabs implantacao-tab" role="tablist">
    <li class="nav-item">
        <a class="nav-link active dados" href="#dados" data-toggle="tab" role="tab" href="#dados" id="nav-dados">Dados</a>
    </li>
    <?php foreach($formQuestion as $key => $formQ) { ?>
        <li class="nav-item" role="tab">
            <a class="nav-link formulario <?= $formQ->getName(); ?>"
               href="<?= "#".$formQ->getName(); ?>"
               data-index="<?= $key; ?>" >
                <?= ucwords(str_replace("_", " ", $formQ->getName())); ?>
            </a>
        </li>
    <?php } ?>
    <li class="nav-item nav-finalizar">
        <a class="nav-link finalizar" href="#finalizar">Finalizar</a>
    </li>
</ul>

<div class="tab-content">
    <div id="dados" class="tab-pane fade container show active" role="tabpanel" aria-labelledby="nav-dados">
        <br>
        <div class="row">
            <div class="col-md-6">

                <div class="form-group">
                    <?= $this->formLabel($form->get('date')); ?>
                    <?= $this->formElement($form->get('date')); ?>
                    <?= $this->formElementErrors($form->get('date')); ?>
                </div>
                <div class="form-group">
                    <?= $this->formLabel($form->get('time')); ?>
                    <?= $this->formElement($form->get('time')); ?>
                    <?= $this->formElementErrors($form->get('time')); ?>
                </div>
                <div class="form-group">
                    <label for="time_end">Horário previsto para término</label>
                    <input type="time"
                           name="time_end"
                           id="time_end"
                           class="form-control" readonly="readonly" autocomplete="off"
                           value="<?= $timeEnd->format('H:i'); ?>">
                </div>
                <div class="form-group text-left">
                    <input type="button" value="Iniciar" class="btn btn-primary iniciarImplantacao hoverable-scale">
                </div>

            </div>
        </div>
    </div>
    <?php
    $index = 0;
    foreach ($formQuestion as $formQ) {
        foreach($perguntas[$formQ->getName()] as $key => $pergunta) { ?>

        <div id="<?= $key; ?>" class="tab-pane fade container question_<?= $index; ?>" role="tabpanel">
            <br>
            <div class="row">
                <div class="col-md-6">

                    <form class="<?= $key; ?>" action="" method="post">
                        <fieldset class='fieldset-preenchido'>
                            <input type="hidden" name="scheduling" value="<?= $deploymentSchedule->getId();  ?>">
                            <?php foreach($pergunta as $p){ echo $p; } ?>

                            <div class="form-group text-left">
                                <input type="button"
                                       value="Pausar"
                                       class="btn btn-danger pausarImplantacao"
                                       data-key="<?= $key; ?>"
                                       data-target="question_<?= $index+1; ?>"
                                       >
                                <?php if($index < count($perguntas)){ ?>
                                        <input type="button"
                                               value="Avançar"
                                               class="btn btn-primary avancarImplantacao"
                                               data-key="<?= $key; ?>"
                                               data-target="question_<?= $index+1; ?>"
                                               >
                                <?php } else { ?>
                                        <input type="button"
                                               value="Finalizar"
                                               class="btn btn-primary avancarImplantacao"
                                               data-key="<?= $key ?>"
                                               data-target="question_<?= $index-2; ?>"
                                               >

                                <?php } ?>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
        <?php $index = $index+1; ?>
        <?php } ?>
    <?php } ?>
    <div id="finalizar" class="container tab-pane fade" role="tabpanel">
        <br>

        <?= $this->form()->openTag($form); ?>
            <div class="row">
                <div class="col-md-6">

                    <div class="form-group">
                        <?= $this->formLabel($form->get('status')); ?>
                        <?= $this->formElement($form->get('status')); ?>
                        <?= $this->formElementErrors($form->get('status')); ?>
                    </div>
                    <div class="form-group text-left">
                        <input type="button" value="voltar" class="btn btn-secondary voltarFormulario hoverable-scale">
                        <?= $this->formElement($form->get('submit')); ?>
                    </div>
                    <input type="hidden" name="tempo-decorrido" class="tempo-decorrido">
                </div>
            </div>
        <?= $this->form()->closeTag(); ?>
    </div>

    <div class="modal fade" id="modalReagendamento">
        <div class="modal-dialog modal-lg">

            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Pausar o agendamento?</h4>
                    <button type="button" class="close hoverable-rotate-moviment"
                            data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                    <p>Você pode pausar o agendamento e continuar outro dia selecionado-o abaixo: </p>
                    <input type="hidden" class="deployment_schedule_id" value="<?= $deploymentSchedule->getId();  ?>">
                    <span class="cliente-hour hidden"><?= $cliente_hour; ?></span>

                    <form method="post" name="reschedule-form" id="reschedule-form">
                        <div class="row">
                            <div class="col-12 col-lg-4">
                                <div class="form-group">
                                    <label for="date">Data</label>
                                    <input type="text"
                                           name="date"
                                           class="form-control pickerdate"
                                           autocomplete="off">
                                </div>
                            </div>
                            <div class="col-12 col-lg-4">
                                <div class="form-group">
                                    <label for="time">Horario</label>
                                    <input type="text"
                                           name="time"
                                           class="form-control timepicker"
                                           autocomplete="off">
                                </div>
                            </div>
                            <div class="col-12 col-lg-4">
                                <div class="form-group">
                                    <label for="time-end">Horario Final</label>
                                    <input type="text"
                                           name="time-end"
                                           class="form-control timepickerEnd"
                                           autocomplete="off"
                                           readonly="readonly">
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
                    <button type="button" class="btn btn-success confirmReschedule">Confirmar</button>
                </div>
            </div>

        </div>
    </div>
</div>