<?php

    $this->headTitle('Agendar Implantação');

    $this->mainMenu()->setActiveItemId('implantation');
    $this->mainMenu()->setActiveListItemId('AGENDA - TÉCNICO');

    $this->pageBreadcrumbs()->setItems([
                'Inicio'=>$this->url('home'),
                'Gerenciamento de Agendamento de Implantação'=>$this->url('deployment_schedule'),
                ]);
?>
<div class="row">
    <?= $this->partial('cms/partial/alert'); ?>
</div>
<div class="row">
    <div class="col">
        <h3>Gerenciamento de Agendamento de Implantação</h3>
    </div>
</div>

<div class="row">
    <?= $this->partial('cms/partial/filter', ['search'=>$search, 'operators' => $operators]); ?>
</div>
<div class="table-responsive top-margin-10">
    <table class="table table-striped table-bordered table-hover dataTables">
        <thead class="thead-dark">
            <tr>
                <th>Cliente</th>
                <th>Data</th>
                <th>Horário</th>
                <th>Término</th>
                <th>Status</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($deploymentSchedules as $deploymentSchedule): ?>
            <tr>
                <td>
                    <a href="<?= $this->url('deployment_schedule',
                                            ['action'=>'view',
                                             'id'=>$deploymentSchedule->getId()]); ?>">
                        <?= $deploymentSchedule->getClientName(); ?>
                    </a>
                </td>
                <td>
                    <?= $deploymentSchedule->getDate()->format('d/m/Y'); ?>
                </td>
                <td>
                    <?= $deploymentSchedule->getTime()->format('H:i'); ?>
                </td>
                <td>
                    <?= $deploymentSchedule->getTimeEnd() ? $deploymentSchedule->getTimeEnd()->format('H:i') : ""; ?>
                </td>
                <td>
                    <?= $deploymentSchedule->getStatusAsString(); ?>
                </td>
                <td>
                    <?php if($deploymentSchedule->getStatus() == 1) { ?>
                    <nobr>
                        <a class="btn btn-sm btn-info hoverable-scale"
                           href="<?= $this->url('deployment_schedule',
                                                ['action'=>'edit',
                                                 'id'=> $deploymentSchedule->getId()]); ?>"
                           title="Iniciar Implantação">
                            <i class="fas fa-cogs"></i>
                        </a>
                    </nobr>
                    <?php } ?>

                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>

