<?php
    $this->headTitle('Visualizar Agendamento');

    $this->mainMenu()->setActiveItemId('implantation');
    $this->mainMenu()->setActiveListItemId('AGENDA - TÉCNICO');

    $this->pageBreadcrumbs()->setItems([
                'Inicio'=>$this->url('home'),
                'Gerenciamento de Agendamento de Implantação'=>$this->url('deployment_schedule'),
                'Visualizar Agendamento'=>$this->url('deployment_schedule', ['action'=>'edit'])
                ]);

?>
<div class="row">
    <?= $this->partial('cms/partial/alert'); ?>
</div>
<div class="row">
    <div class="col-12 col-md-6">
        <h3>Visualizar Agendamento </h3>
        <table class="table table-striped table-bordered">
            <tr>
                <th>Cliente:</th>
                <td><?= $this->escapeHtml($deploymentSchedule->getClientName()); ?></td>
            </tr>
            <tr>
                <th>Data:</th>
                <td><?= $this->escapeHtml($deploymentSchedule->getDate()->format('d/m/Y')); ?></td>
            </tr>
            <tr>
                <th>Horário:</th>
                <td><?= $this->escapeHtml($deploymentSchedule->getTime()->format('H:i')); ?></td>
            </tr>
            <?php if($deploymentSchedule->getTimeEnd()) { ?>
            <tr>
                <th>Horário de Término:</th>
                <td><?= $this->escapeHtml($deploymentSchedule->getTimeEnd()->format('H:i')); ?></td>
            </tr>
            <?php } ?>
            <tr>
                <th>Status:</th>
                <td><?= $this->escapeHtml($deploymentSchedule->getStatusAsString()); ?></td>
            </tr>
        </table>
    </div>
    <?php if($deploymentSchedule->getStatus() == 0) { ?>
        <div class="col-12 col-md-6">
            <h3>Resumo de implantação</h3>
            <table class="table table-striped table-bordered">
                <?php foreach($result as $key => $resultado): ?>
                        <tr>
                            <td class="text-center" colspan="2"><?= $key; ?></td>
                        </tr>
                    <?php foreach($resultado as $r): ?>
                        <tr>
                            <?php
                                $name = $this->escapeHtml($r['name']);

                                if(!empty($r['label'])):
                                    $echo = $this->escapeHtml($r['label']);
                                else:
                                     $echo = $this->escapeHtml($r['value']);
                                 endif;
                            ?>

                            <?php if (strtolower($key) == strtolower($name)) { ?>
                                <td></td>
                            <?php } else { ?>

                                <?php if (strtolower($name) == 'se a resposta for sim, responda') { ?>
                                    <td></td>
                                <?php } else { ?>
                                    <td><?= $lastName != $name ? $this->escapeHtml($name) : ""; ?></td>
                                <?php } ?>

                            <?php } ?>

                            <td><?= $this->escapeHtml($echo); ?></td>
                            <?php $lastName = $name; ?>
                        </tr>
                    <?php endforeach; ?>
                <?php endforeach; ?>
            </table>
        </div>
    <?php } ?>
</div>