<?php

    $this->headTitle('Editar Setor');

    $this->mainMenu()->setActiveItemId('management');
    $this->mainMenu()->setActiveListItemId('Setores');

    $this->pageBreadcrumbs()->setItems([
                'Inicio'=>$this->url('home'),
                'Gerenciamento de Setores'=>$this->url('departaments'),
                'Editar Setor'=>$this->url('departaments', ['action'=>'edit', 'id'=>$departament->getId()])
                ]);

        $form->get('name')->setAttributes([
            'class'=>'form-control',
            'placeholder'=>'Desenvolvimento'
            ]);

        $form->get('status')->setAttributes([
            'class'=>'form-control'
            ]);

        $form->get('submit')
                ->setAttributes(['class'=>'btn btn-danger'])
                ->setValue('Alterar');

        $form->prepare();
?>
<div class="row">
    <?= $this->partial('cms/partial/alert'); ?>
</div>
<div class="row">
    <div class="col">
        <h3>Editar setor <?= $this->escapeHtml($departament->getName()) ?></h3>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>

        <div class="material-switch form-group">
            <span>Status</span><br>
            <?= $this->formCheckbox($form->get('status')); ?>
            <?= $this->formLabel($form->get('status')); ?>
            <?= $this->formElementErrors($form->get('status')); ?>
            <span class='status_description'></span>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('name')); ?>
            <?= $this->formElement($form->get('name')); ?>
            <?= $this->formElementErrors($form->get('name')); ?>
        </div>


        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>

