<?php
    $this->headTitle('Setores');

    $this->mainMenu()->setActiveItemId('management');
    $this->mainMenu()->setActiveListItemId('Setores');

    $this->pageBreadcrumbs()->setItems([
                'Inicio'=>$this->url('home'),
                'Gerenciamento de Setores'=>$this->url('departaments'),
                ]);
?>
<div class="row">
    <?= $this->partial('cms/partial/alert'); ?>
</div>
<div class="row">

    <div class="col">
        <h3>Gerenciamento de Setores</h3>
    </div>
    <div class="col text-right">
        <a class="btn btn-sm btn-outline-primary rounded-circle hoverable-rotate hoverable-rotate-moviment" href="
            <?= $this->url('departaments', ['action'=>'add']); ?>" title="Adicionar">
            <i class="fas fa-plus"></i>
        </a>
    </div>

</div>
<div class="row">
    <?= $this->partial('cms/partial/filter', ['search'=>$search, 'operators' => $operators]); ?>
</div>

<div class="table-responsive top-margin-10">
    <table class="table table-striped table-bordered table-hover dataTables">
        <thead class="thead-dark">
            <tr>
                <th>Nome</th>
                <th>Status</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($departaments as $departament): ?>
            <tr>
                <td>
                    <a href="<?= $this->url('departaments', ['action'=>'view', 'id'=>$departament->getId()]); ?>">
                        <?= $this->escapeHtml($departament->getName()); ?>
                    </a>
                </td>
                <td>
                    <div class="status_string_<?= $departament->getId(); ?>">
                        <?= $this->escapeHtml($departament->getStatusAsString()); ?>
                    </div>
                    <div class="material-switch">
                        <input class="status-index" type="checkbox" name="status"
                               value="<?= $departament->getStatus() ;?>"
                               data-status="<?= $this->escapeHtml($departament->getStatusAsString()); ?>"
                               data-id="<?= $departament->getId(); ?>"
                               id="status_<?= $departament->getId(); ?>"
                               >
                        <label for="status_<?= $departament->getId(); ?>"></label>
                    </div>
                </td>
                <td>
                    <a class="btn btn-sm btn-info hoverable-scale"
                       href="<?= $this->url('departaments', ['action'=>'edit', 'id'=>$departament->getId()]); ?>"
                       title="Editar">
                        <i class="far fa-edit"></i>
                    </a>
                    <a class="btn btn-sm btn-danger delete-action hoverable-scale"
                       data-id="<?= $departament->getId(); ?>"
                       href="#"
                       title="Remover">
                        <i class="fa fa-trash"></i>
                    </a>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
