<?php

    $this->headTitle('Alterar de Pergunta');

    $this->mainMenu()->setActiveItemId('quiz');
    $this->mainMenu()->setActiveListItemId('Perguntas');

    $this->pageBreadcrumbs()
         ->setItems(['Inicio'=>$this->url('home'),
                     'Gerenciamento de Formulário de Perguntas'=>$this->url('quiz'),
                     'Editar de Pergunta'=>$this->url('quiz', ['action'=>'edit'])]);

    $form->get('id_question_form')->setAttributes([
        'class'=>'form-control',
        'placeholder'=>'Formulário'
        ]);

    $form->get('name')->setAttributes([
        'class'=>'form-control',
        'placeholder'=>'Nome',
        ]);

    $form->get('type')->setAttributes([
        'class'=>'form-control type',
        ]);

    $form->get('sequence')->setAttributes([
        'class'=>'form-control',
        ]);

    $form->get('required')->setAttributes([
        'class'=>'form-control'
        ]);

    $form->get('status')->setAttributes([
        'class'=>'form-control'
        ]);

    $form->get('submit')
         ->setAttributes(['class'=>'btn btn-danger form-control'])
         ->setValue('Alterar');

    $form->prepare();
?>
<div class="row">
    <?= $this->partial('cms/partial/alert'); ?>
</div>
<h3>Editar Pergunta: <?= $this->escapeHtml($question->getName()) ?></h3>

<?= $this->form()->openTag($form); ?>

    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <?= $this->formLabel($form->get('id_question_form')); ?>
                <?= $this->formElement($form->get('id_question_form')); ?>
                <?= $this->formElementErrors($form->get('id_question_form')); ?>
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <?= $this->formLabel($form->get('type')); ?>
                <?= $this->formElement($form->get('type')); ?>
                <?= $this->formElementErrors($form->get('type')); ?>
            </div>
        </div>
        <div class="col-md-3">
            <div class="material-switch form-group">
                <span>Obrigatório</span><br>
                <?= $this->formCheckbox($form->get('required')); ?>
                <?= $this->formLabel($form->get('required')); ?>
                <?= $this->formElementErrors($form->get('required')); ?>
                <span class='status_description_required'></span>
            </div>
        </div>
    </div>
    <div class="row">

        <div class="col-md-6">
            <div class="form-group">
                <?= $this->formLabel($form->get('name')); ?>
                <?= $this->formElement($form->get('name')); ?>
                <?= $this->formElementErrors($form->get('name')); ?>
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <?= $this->formLabel($form->get('sequence')); ?>
                <?= $this->formElement($form->get('sequence')); ?>
                <?= $this->formElementErrors($form->get('sequence')); ?>
            </div>
        </div>
        <div class="col-md-3">
            <div class="material-switch form-group">
                <span>Status</span><br>
                <?= $this->formCheckbox($form->get('status')); ?>
                <?= $this->formLabel($form->get('status')); ?>
                <?= $this->formElementErrors($form->get('status')); ?>
                <span class='status_description_form'></span>
            </div>
        </div>
    </div>

<hr>
<h3>Respostas</h3>
<div class="row partial">
    <?= $this->partial('quiz/question-field/add-partial', ['fields' => $fields]); ?>
</div>

<div class="row">
    <div class="col-md-2">
        <div class="form-group">
            <label></label>
            <?= $this->formElement($form->get('submit')); ?>
        </div>
    </div>
</div>

<?= $this->form()->closeTag(); ?>
