<?php

    $this->headTitle('Formulário de Perguntas');

    $this->mainMenu()->setActiveItemId('quiz');
    $this->mainMenu()->setActiveListItemId('Perguntas');

    $this->pageBreadcrumbs()
         ->setItems(['Inicio'=>$this->url('home'),
                     'Gerenciamento de Formulário de Perguntas'=>$this->url('quiz')]);
?>
<div class="row">
    <?= $this->partial('cms/partial/alert'); ?>
</div>
<div class="row">
    <div class="col col-md-8">
        <h3>Gerenciamento de Formulário de Perguntas</h3>
    </div>
    <div class="col text-right">
        <a class="btn btn-sm btn-outline-primary rounded-circle hoverable-rotate hoverable-rotate-moviment" href="
            <?= $this->url('quiz', ['action'=>'add']); ?>" title="Adicionar">
            <i class="fas fa-plus"></i>
        </a>
    </div>
</div>
<!-- name, form, order, required, status.and question_form_bond -->
<div class="row">
    <?= $this->partial('cms/partial/filter', ['search'=>$search, 'operators' => $operators]); ?>
</div>
<div class="table-responsive top-margin-10">
    <table class="table table-striped table-bordered table-hover dataTables">
        <thead class="thead-dark">
            <tr>
                <th>Formulário</th>
                <th>Nome</th>
                <th>Tipo</th>
                <th>Ordem</th>
                <th>Obrigatório</th>
                <th>Status</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($questionnaires as $quiz): ?>
            <tr>
                <td>
                    <?= $quiz->getQuestionFormAsString(); ?>
                </td>
                <td>
                    <a href="<?= $this->url('quiz', ['action'=>'view', 'id'=>$quiz->getId()]); ?>">
                        <?= $this->escapeHtml($quiz->getName()); ?>
                    </a>
                </td>
                <td>
                    <?= $quiz->getTypeAsString(); ?>
                </td>
                <td>
                    <?= $quiz->getSequence(); ?>
                </td>
                <td>
                    <?= $quiz->getRequiredAsString(); ?>
                </td>
                <td>
                    <?= $quiz->getStatusAsString(); ?>
                </td>
                <td>
                    <nobr>
                        <a class="btn btn-sm btn-info hoverable-scale"
                           href="<?= $this->url('quiz', ['action'=>'edit', 'id'=>$quiz->getId()]); ?>"
                           title="Editar">
                            <i class="far fa-edit"></i>
                        </a>
                        <a class="btn btn-sm btn-danger delete-action hoverable-scale"
                           data-id="<?= $quiz->getId(); ?>"
                           href="#"
                           title="Remover">
                            <i class="fa fa-trash"></i>
                        </a>
                    </nobr>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>

