<?php
    $this->headTitle('Visualizar Pergunta');

    $this->mainMenu()->setActiveItemId('quiz');
    $this->mainMenu()->setActiveListItemId('Perguntas');

    $this->pageBreadcrumbs()->setItems([
                'Inicio'=>$this->url('home'),
                'Gerenciamento de Formulário de Perguntas'=>$this->url('quiz'),
                'Visualizar Pergunta'=>$this->url('quiz', ['action'=>'edit'])
                ]);

?>
<div class="row">
    <?= $this->partial('cms/partial/alert'); ?>
</div>
<h3>Visualizar Pergunta </h3>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
            <tr>
                <th>Formulário:</th>
                <td><?= $this->escapeHtml($question->getQuestionFormAsString()); ?></th>
            </tr>
             <tr>
                <th>Nome:</th>
                <td><?= $this->escapeHtml($question->getName()); ?></th>
            </tr>
            <tr>
                <th>Tipo:</th>
                <td><?= $this->escapeHtml($question->getTypeAsString()); ?></th>
            </tr>
            <tr>
                <th>Sequência:</th>
                <td><?= $this->escapeHtml($question->getSequence()); ?></th>
            </tr>
            <tr>
                <th>Obrigatório:</th>
                <td><?= $this->escapeHtml($question->getRequiredAsString()); ?></th>
            </tr>
            <tr>
                <th>Status:</th>
                <td><?= $this->escapeHtml($question->getStatusAsString()); ?></th>
            </tr>
        </table>
    </div>
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
            <tr>
                <th>Exemplo:</th>
                <td><?= $input; ?></td>
            </tr>
        </table>
    </div>
</div>