<?php

    $this->headTitle('Visualizar Unidade');

    $this->mainMenu()->setActiveItemId('management');
    $this->mainMenu()->setActiveListItemId('Unidades');

    $this->pageBreadcrumbs()->setItems([
                'Inicio'=>$this->url('home'),
                'Gerenciamento de Unidades'=>$this->url('organizations'),
                'Visualizar Unidade'=>$this->url('organizations', ['action'=>'view', 'id'=>$organization->getId()])
                ]);
?>

<div class="row">
    <?= $this->partial('cms/partial/alert'); ?>
</div>
<h3>Visualizar Unidade </h3>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
            <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($organization->getId()); ?></th>
            </tr>
            <tr>
                <th>Name:</th>
                <td><?= $this->escapeHtml($organization->getName()); ?></th>
            </tr>
            <tr>
                <th>Status:</th>
                <td><?= $this->escapeHtml($organization->getStatusAsString()); ?></th>
            </tr>
        </table>
    </div>

<?php if (!empty($hour) || $hour !== "") { ?>

    <div class="col-md-6 table-responsive">
        <table class="table table-striped table-bordered">
            <thead class="thead-dark">
                <td>Dia</td>
                <td>Inicio - Manhã</td>
                <td>Fim - Manhã</td>
                <td>Inicio - Tarde</td>
                <td>Fim - Tarde</td>
            </thead>
            <tbody>
                <?php foreach ($hour as $h) { ?>
                    <tr>
                        <td><?= $h->getDay(); ?></td>
                        <td><?= $h->getMorningStartTime()->format('H:i'); ?></td>
                        <td><?= $h->getMorningClosingTime()->format('H:i'); ?></td>
                        <td><?= $h->getAfternoonStartTime()->format('H:i'); ?></td>
                        <td><?= $h->getAfternoonClosingTime()->format('H:i'); ?></td>
                    </tr>

                <?php } ?>
            </tbody>
        </table>
    </div>
<?php } ?>
</div>