<?php

    $this->headTitle('Confirmar Implantação');
    $this->headLink()
          ->prependStylesheet($this->basePath('css/min/jquery.timepicker.min.css'));

    $this->mainMenu()->setActiveItemId('implantation');
    $this->mainMenu()->setActiveListItemId('AGENDA - TÉCNICO');

    $this->pageBreadcrumbs()->setItems([
                'Inicio'=>$this->url('home'),
                'Gerenciamento de Agendamentos do Cliente'=>$this->url('client_scheduling'),
                'Confirmar Agendamento'=>$this->url('client_scheduling', ['action'=>'confirm'])
                ]);

    $data  = new Datetime($scheduling[0]['atdDtcadastro']['date']);
    $hora  = new Datetime($scheduling[0]['atdHorainicio']['date']);
    $horaE = new Datetime($scheduling[0]['atdHorafinal']['date']);

    $form->get('id_client')->setAttributes([
        'class'=>'form-control',
        'placeholder'=>'Cliente',
        'value' => $scheduling[0]['atdIdcliente'],
        'readonly' => 'readonly'
        ]);

    $form->get('date')->setAttributes([
        'class'=>'form-control',
        'readonly' => 'readonly',
        'autocomplete' => 'off'
        ]);

    $form->get('time')->setAttributes([
        'class'=>'form-control',
        'readonly' => 'readonly',
        'disabled' => 'disabled',
        'autocomplete' => 'off'
        ]);

    $form->get('time_end')->setAttributes([
        'class'=>'form-control timepickerEnd',
        'readonly' => 'readonly',
        'disabled' => 'disabled',
        'autocomplete' => 'off'
        ]);

    $form->get('submit')
         ->setAttributes(['class'=>'btn btn-success'])
         ->setValue('Confirmar');

    $form->prepare();

?>
<div class="row">
    <?= $this->partial('cms/partial/alert'); ?>
</div>

<h3> Confirmar Agendamento: <?= $scheduling[0]['cliNome']; ?></h3>

<?= $this->form()->openTag($form); ?>

    <input type="hidden" name="id_attendance_crm" value="<?= $scheduling[0]['atdIdatendimento']; ?>">
    <input type="hidden" name="id_client" value="<?= $scheduling[0]['atdIdcliente']; ?>">
    <input type="hidden" name="data" value="<?= $data->format('d/m/Y'); ?>">
    <input type="hidden" name="time" value="<?= $hora->format('H:i'); ?>">
    <input type="hidden" name="time_end_init"  value="<?= $horaE->format('H:i'); ?>">

    <div class="row">
        <div class="col-12 col-lg-6 add-half">
            <table class="table table-striped table-bordered">
                <tr>
                    <th>Telefone:</th>
                    <td>
                        <a href="tel:<?= $scheduling[0]['cliFone1']; ?>">
                            <?= $scheduling[0]['cliFone1']; ?>
                        </a>
                    </td>
                </tr>
                <tr>
                    <th>Data:</th>
                    <td><?= $this->escapeHtml($data->format('d/m/Y')); ?></td>
                </tr>
                <tr>
                    <th>Horário:</th>
                    <td><?= $this->escapeHtml($hora->format('H:i')); ?></td>
                </tr>
                <tr>
                    <th>Horário de Término:</th>
                    <td><?= $this->escapeHtml($horaE->format('H:i')); ?></td>
                </tr>
                <tr>
                    <th>Horas disponiveis:</th>
                    <td class="cliente-hour"><?= $horas_cliente; ?></td>
                </tr>
            </table>

        </div>
        <div class="col-12 col-lg-6">
            <div class="row hidden">
                <div class="col-md-12">
                    <div class="form-group">
                        <?= $this->formLabel($form->get('date')); ?>
                        <?= $this->formElement($form->get('date')); ?>
                        <?= $this->formElementErrors($form->get('date')); ?>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <?= $this->formLabel($form->get('time')); ?>
                        <?= $this->formElement($form->get('time')); ?>
                        <?= $this->formElementErrors($form->get('time')); ?>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <?= $this->formLabel($form->get('time_end')); ?>
                        <?= $this->formElement($form->get('time_end')); ?>
                        <?= $this->formElementErrors($form->get('time_end')); ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-12">
            <div class="row">
                <div class="col-6 text-left">
                    <input type="button" value="Reagendar" class="btn btn-danger reagendar hoverable-scale">
                    <?= $this->formElement($form->get('submit')); ?>
                </div>
                <div class="col-6 text-left">
                    <div class="form-group text-left">
                        <input type="hidden" name="client_name" value="<?= $scheduling[0]['cliNome']; ?>">
                        <input type="hidden" name="client_email" value="<?= $scheduling[0]['cliEmail']; ?>">
                    </div>
                </div>
            </div>
        </div>
    </div>
<?= $this->form()->closeTag(); ?>


