<?php

    $this->headTitle('Agenda - Cliente');

    $this->mainMenu()->setActiveItemId('implantation');
    $this->mainMenu()->setActiveListItemId('AGENDA - TÉCNICO');

    $this->pageBreadcrumbs()->setItems([
                'Inicio'=>$this->url('home'),
                'Gerenciamento de Agendamentos do Cliente'=>$this->url('client_scheduling'),
                ]);
?>
<div class="row">
    <?= $this->partial('cms/partial/alert'); ?>
</div>
<div class="row">
    <div class="col">
        <h3>Gerenciamento de Agendamentos do Cliente</h3>
    </div>
</div>

<div class="row">
    <?= $this->partial('cms/partial/filter', ['search'=>$search, 'operators' => $operators]); ?>
</div>
<div class="table-responsive top-margin-10">
    <table class="table table-striped table-bordered table-hover dataTables">
        <thead class="thead-dark">
            <tr>
                <th>Cliente</th>
                <th>Dia    </th>
                <th>Horário</th>
                <th>Ações  </th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($datas as $data): ?>
                <?php $dia = new DateTime($data['atdDtcadastro']["date"]); ?>
                <?php $hora = new DateTime($data['atdHorainicio']["date"]); ?>
            <tr>
                <td>
                    <?= $data['cliNome']; ?>
                </td>
                <td>
                    <?= $dia->format('d/m/Y'); ?>
                </td>
                <td>
                    <?= $hora->format('H:i'); ?>
                </td>
                <td>
                    <nobr>
                        <a class="btn btn-sm btn-success hoverable-scale"
                           href="<?= $this->url('client_scheduling',
                                                ['action'=>'confirm',
                                                 'id'=>$data['atdIdatendimento']]); ?>"
                           title="Confirmar Agendamento">
                            <i class="far fa-calendar-check"></i>
                        </a>
                    </nobr>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
