<?php
    $this->headTitle('Visualizar Agendamento');

    $this->mainMenu()->setActiveItemId('deployment_schedule');
    $this->mainMenu()->setActiveListItemId('Agendamento');

    $this->pageBreadcrumbs()->setItems([
                'Inicio'=>$this->url('home'),
                'Gerenciamento de Agendamento de Implantação'=>$this->url('deployment_schedule'),
                'Visualizar Agendamento'=>$this->url('deployment_schedule', ['action'=>'edit'])
                ]);

?>
<div class="row">
    <?= $this->partial('cms/partial/alert'); ?>
</div>
<h3>Visualizar Agendamento </h3>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
             <tr>
                <th>Cliente:</th>
                <td><?= $this->escapeHtml($deploymentSchedule->getIdClient()); ?></th>
            </tr>
            <tr>
                <th>Data:</th>
                <td><?= $this->escapeHtml($deploymentSchedule->getDate()->format('d/m/Y')); ?></th>
            </tr>
            <tr>
                <th>Horário:</th>
                <td><?= $this->escapeHtml($deploymentSchedule->getTime()->format('H:i')); ?></th>
            </tr>
            <?php if($deploymentSchedule->getTimeEnd()) { ?>
            <tr>
                <th>Horário de Término:</th>
                <td><?= $this->escapeHtml($deploymentSchedule->getTimeEnd()->format('H:i')); ?></th>
            </tr>
            <?php } ?>
            <tr>
                <th>Status:</th>
                <td><?= $this->escapeHtml($deploymentSchedule->getStatusAsString()); ?></th>
            </tr>
        </table>
    </div>
</div>