<div class="jumbotron">
    <h1 class="text-center">
        Bem-vindo ao mais novo <br>
        <span class="red-csec">Csec CRM</span>
    </h1>
    <p>
        Parabéns! Você está olhando para o mais novo ambiente de Gerenciamento de empresas da Csec.
        Esse portal está sendo desenvolvido com o propósito de revigorar o gerenciamento de dados
        utilizando as ferramentas mais robustas e atuais do mercado.

    </p>
</div>
