<?php
    $this->headTitle('Cargos');

    $this->mainMenu()->setActiveItemId('management');
    $this->mainMenu()->setActiveListItemId('Cargos');

    $this->pageBreadcrumbs()->setItems([
                'Inicio'=>$this->url('home'),
                'Gerenciamento de Cargos'=>$this->url('jobs'),
                ]);
?>
<div class="row">
    <?= $this->partial('cms/partial/alert'); ?>
</div>
<div class="row">

    <div class="col">
        <h3>Gerenciamento de Cargos</h3>
    </div>
    <div class="col text-right">
        <a class="btn btn-sm btn-outline-primary rounded-circle hoverable-rotate hoverable-rotate-moviment" href="
            <?= $this->url('jobs', ['action'=>'add']); ?>" title="Adicionar">
            <i class="fas fa-plus"></i>
        </a>
    </div>

</div>
<div class="row">
    <?= $this->partial('cms/partial/filter', ['search'=>$search, 'operators' => $operators]); ?>
</div>

<div class="table-responsive top-margin-10">
    <table class="table table-striped table-bordered table-hover dataTables">
        <thead class="thead-dark">
            <tr>
                <th id="nome">Nome</th>
                <th id="cargo">Cargo Superior</th>
                <th id="status">Status</th>
                <th id="acoes">Ações</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($jobs as $job): ?>
            <tr>
                <td>
                    <a href="<?= $this->url('jobs', ['action'=>'view', 'id'=>$job->getId()]); ?>">
                        <?= $this->escapeHtml($job->getName()); ?>
                    </a>
                </td>
                <td><?= $this->escapeHtml($job->getIdTopJob()); ?></td>
                <td>
                    <div class="status_string_<?= $job->getId(); ?>">
                        <?= $this->escapeHtml($job->getStatusAsString()); ?>
                    </div>
                    <div class="material-switch">
                        <input class="status-index" type="checkbox" name="status"
                               value="<?= $job->getStatus() ;?>"
                               data-status="<?= $this->escapeHtml($job->getStatusAsString()); ?>"
                               data-id="<?= $job->getId(); ?>"
                               id="status_<?= $job->getId(); ?>"
                               >
                        <label for="status_<?= $job->getId(); ?>"></label>
                    </div>
                </td>
                <td>
                    <a class="btn btn-sm btn-info hoverable-scale"
                       href="<?= $this->url('jobs', ['action'=>'edit', 'id'=>$job->getId()]); ?>"
                       title="Editar">
                        <i class="far fa-edit"></i>
                    </a>
                    <a class="btn btn-sm btn-danger delete-action hoverable-scale"
                       data-id="<?= $job->getId(); ?>"
                       href="#" title="Remover">
                        <i class="fa fa-trash"></i>
                    </a>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
