<?php
    $this->headTitle('Visualizar Cargo');

    $this->mainMenu()->setActiveItemId('management');
    $this->mainMenu()->setActiveListItemId('Cargos');

    $this->pageBreadcrumbs()->setItems([
            'Inicio'=>$this->url('home'),
            'Gerenciamento de Cargos'=>$this->url('jobs'),
            'Visualizar Cargo'=>$this->url('jobs', ['action'=>'view', 'id'=>$job->getId()])
            ]);
?>

<div class="row">
    <?= $this->partial('cms/partial/alert'); ?>
</div>
<h3>Visualizar Cargo </h3>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
             <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($job->getId()); ?></th>
            </tr>
            <tr>
                <th>Name:</th>
                <td><?= $this->escapeHtml($job->getName()); ?></th>
            </tr>
            <tr>
                <th>Cargo Superior:</th>
                <td><?= $this->escapeHtml($job->getIdTopJob()); ?></th>
            </tr>
            <tr>
                <th>Status:</th>
                <td><?= $this->escapeHtml($job->getStatusAsString()); ?></th>
            </tr>
        </table>
    </div>
</div>