
<?php
    $this->headTitle('Redefinir senha');

    $form->get('email')
         ->setAttributes([
                'class'=>'mat-input',
                'required' => true,
            ])
         ->setLabelAttributes([
                'class' => 'mat-label'
         ]);

    $form->get('captcha')
         ->setAttributes([
                'class'=>'mat-input',
                'required' => true,
            ])
         ->setLabelAttributes([
                'class' => 'mat-label'
         ]);

    $form->get('submit')
         ->setAttributes([
                'class'=>'btn btn-lg btn-danger btn-block'
    ]);
    $form->prepare();
?>

<div class="row">
    <div class="col m12 text-center">
        <h1 class="form-signin-heading-reset">
            <strong>Csec Sistemas</strong>
        </h1>
    </div>
    <div class="w-100"></div>
    <div class="col-md-6 offset-md-3">

        <?= $this->form()->openTag($form); ?>

            <div class="text-center">
                <p class="info">Informe o seu endereço de e-mail abaixo para redefinir sua senha.</p>
            </div>

            <div class="mat-div">
                <?= $this->formLabel($form->get('email')); ?>
                <?= $this->formElement($form->get('email')); ?>
            </div>
            <div class="mat-div captcha">
                <?= $this->formLabel($form->get('captcha')); ?>
                <?= $this->formElement($form->get('captcha')); ?>
            </div>

            <div class="row">
                <div class="col m4">
                        <a class="btn btn-lg btn-danger btn-block"
                           href="<?= $this->url('login') ?>">
                             <i class="fas fa-arrow-alt-circle-left"></i>   Voltar
                        </a>
                    </button>
                </div>
                <div class="col m8">
                    <button class="btn btn-lg btn-danger btn-block" type="submit">
                         <i class="fas fa-unlock-alt"></i> Resetar Senha
                    </button>
                </div>
            </div>
            <?= $this->formElement($form->get('csrf')); ?>

        <?= $this->form()->closeTag(); ?>

    </div>
</div>
