<?php
    $this->headTitle('Editar Permissão');

    $this->mainMenu()->setActiveItemId('admin');
    $this->mainMenu()->setActiveListItemId('Permissões');

    $this->pageBreadcrumbs()->setItems([
                'Inicio'=>$this->url('home'),
                'Gerenciamento de Permissões'=>$this->url('permissions'),
                'Editar Permissão'=>$this->url('permissions', ['action'=>'edit', 'id'=>$permission->getId()])
                ]);

    $form->get('name')->setAttributes([
        'class'=>'form-control',
        'placeholder'=>'Digite um Nome'
        ]);

    $form->get('description')->setAttributes([
        'class'=>'form-control',
        'placeholder'=>'Digite uma descrição'
        ]);

    $form->get('submit')
            ->setAttributes(['class'=>'btn btn-danger'])
            ->setValue('Editar');

    $form->prepare();
?>
<div class="row">
    <?= $this->partial('cms/partial/alert'); ?>
</div>
<div class="row">
    <div class="col">
        <h3>Editar Permissão <?= $this->escapeHtml($permission->getName()); ?></h3>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('name')); ?>
            <?= $this->formElement($form->get('name')); ?>
            <?= $this->formElementErrors($form->get('name')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('description')); ?>
            <?= $this->formElement($form->get('description')); ?>
            <?= $this->formElementErrors($form->get('description')); ?>
        </div>

        <?= $this->formElement($form->get('csrf')); ?>

        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>

