<?php
    $this->headTitle('Visualizar Permissão');

    $this->mainMenu()->setActiveItemId('admin');
    $this->mainMenu()->setActiveListItemId('Permissões');

    $this->pageBreadcrumbs()->setItems([
                'Inicio'=>$this->url('home'),
                'Gerenciamento de Permissões'=>$this->url('permissions'),
                'Visualizar Permissão'=>$this->url('permissions', ['action'=>'view', 'id'=>$permission->getId()])
                ]);
?>
<div class="row">
    <?= $this->partial('cms/partial/alert'); ?>
</div>
<h3>Visualizar Permissão</h3>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
             <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($permission->getId()) ?></th>
            </tr>
            <tr>
                <th>Nome:</th>
                <td><?= $this->escapeHtml($permission->getName()) ?></th>
            </tr>
            <tr>
                <th>Descrição:</th>
                <td><?= $this->escapeHtml($permission->getDescription()) ?></th>
            </tr>
            <tr>
                <th>Data de Criação:</th>
                <td><?= $this->escapeHtml($permission->getDateCreated()) ?></th>
            </tr>
        </table>
    </div>
</div>